[tool.poetry]
name = "homework2"
version = "0.1.0"
description = "Homework 2 project"
authors = ["YuriiOdynets <yuriiodynets@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
